# Generated by Django 5.1.5 on 2025-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.TextField(default='uncategorized'),
        ),
    ]
