# Generated by Django 5.1.5 on 2025-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0002_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='importance',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-importance', '-published_date'], name='news_core_a_importa_7953e6_idx'),
        ),
    ]
