# Generated by Django 5.1.5 on 2025-02-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0003_article_importance_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='news_core_a_importa_7953e6_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='importance',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='news_core_a_publish_cbded8_idx'),
        ),
    ]
