# Generated by Django 5.1.5 on 2025-02-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0004_remove_article_news_core_a_importa_7953e6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='news_core_a_publish_cbded8_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='wordcount',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date', '-wordcount'], name='news_core_a_publish_915a09_idx'),
        ),
    ]
