# Generated by Django 5.1.5 on 2025-02-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0005_remove_article_news_core_a_publish_cbded8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='news_core_a_publish_915a09_idx',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='news_core_a_publish_cbded8_idx'),
        ),
    ]
