# Generated by Django 5.1.5 on 2025-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0006_remove_article_news_core_a_publish_915a09_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='apiUrl',
            field=models.TextField(default=''),
        ),
    ]
