# Generated by Django 5.1.5 on 2025-02-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0007_article_apiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
    ]
