# Generated by Django 5.1.5 on 2025-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_core', '0008_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
    ]
